### ISSUE TITLE
link: macro does link to correct commit/branch for branches that are not default branch

### ISSUE THREAD

**Issue by mkobit** [christiangalsterer/bitbucket-asciidoc-plugin#14]
Similar to https://github.com/christiangalsterer/bitbucket-asciidoc-plugin/issues/12, when linking to a different document with `link:my_dir/my_doc.adoc` it does not factor that I am not using the default branch.

**Comment by christiangalsterer** [comment]
Are you using latest version 2.3.2?

**Comment by mkobit** [comment]
Yup. I will run through a more detailed reproduction case again to make sure that it is actually behaving this way and not just me missing something.

**Comment by christiangalsterer** [comment]
ok great

**Comment by mkobit** [comment]
I looked back at this and was unable to reproduce.
