### ISSUE TITLE
Links are broken in AsciiDoc version 3.1.0

### ISSUE THREAD

**Issue by syee514** [christiangalsterer/bitbucket-asciidoc-plugin#20]
Hello,

With AsciiDoc version 3.1.0, after clicking on a link in an AsciiDoc document, the link does not go to the correct target but lists the files in the folder. AsciiDoc 3.1.0 determines the link to be <URL PATH>/#_<anchor name>?at=refs/heads/master which does not exist whereas AsciiDoc 3.0.0 determines the link to be <URL PATH>/<filename>#_<anchor name> which exists and the target is displayed.

Can you please resolve the issue so that the links are followed.

Thanks!

**Comment by ar613** [comment]
This looks like an issue with #19 

```
     /**
      * Handle links and convert relative locations to absolute URLs
      */
     function handleLinks($content, asciiDocRawUrl, commitHash) {
         $('a', $content).each(function () {
             if(!this.getAttribute('href').startsWith('http'))
                 this.href = getBaseUrl(asciiDocRawUrl) + this.getAttribute('href') + '?at=' + commitHash;
         });
     }
```

**Comment by christiangalsterer** [comment]
I just gave it a try and it worked for me using the following syntax.

```
==== Include Using Relative Path

include::include/include.adoc[]

==== Include Using Variables

include::{includedir}/include.adoc[]
```

I noticed that there is an issue with table of contents.

Can you provide an example of the link syntax you use along with the Bitbucket version.

**Comment by syee514** [comment]
The issue is with the table of contents where by the table of content links are not followed.
The Bitbucket version is 5.5.1.

**Comment by christiangalsterer** [comment]
thanks for the update. Will look into it to create proper links for TOC

**Comment by christiangalsterer** [comment]
A new version 3.1.1 is available on the Atlassian Marketplace

**Comment by christiangalsterer** [comment]
A new version 2.4.1 is available on the Atlassian Marketplace
