### ISSUE TITLE
AsciiDoc 3.1.1: Inline links are broken

### ISSUE THREAD

**Issue by syee514** [christiangalsterer/bitbucket-asciidoc-plugin#21]
Hello,

Using Bitbucket 5.5..1, with AsciiDoc 3.1.1, the inline link is incorrect. If you hover over a link, the PATH will be \<path\>/#\<anchor name\>?at=/refs/heads/master. You will be presented the folder list after clicking on this link. In AsciiDoc 3.0.0, if you hover over a link, the PATH will be \<path\>/\<filename\>#\<anchor\>, Clicking on this link, the target is presented.

Attached is a sample asciidoc file.

Thank-you!
[sample_asciidoc.txt](https://github.com/christiangalsterer/bitbucket-asciidoc-plugin/files/1483998/sample_asciidoc.txt)

**Comment by christiangalsterer** [comment]
Confirmed, will look for a bugfix in the next days.

**Comment by christiangalsterer** [comment]
New version 3.1.2 and 2.4.2 are available in the Atlassian Marketplace.
