### ISSUE TITLE
Relative images are not resolved

### ISSUE THREAD

**Issue by mwilmes** [christiangalsterer/bitbucket-asciidoc-plugin#4]
Image references like

image::sunset.jpg[]

are not resolved. There is a raw display mode for files in Bitbucket but the URL but those are not relative to the asciidoc document. Hence images are not displayed.

**Comment by christiangalsterer** [comment]
In general it should be possible to modify the output HTML so that relative URLs are resolved in URLs matching the bitbucket URLs. I try to look into this the next days.

**Comment by christiangalsterer** [comment]
A fix is available in version 2.2.0.

**Comment by mwilmes** [comment]
Brilliant. Thank you!
