### ISSUE TITLE
Plugin seems to render build.gradle files and fails

### ISSUE THREAD

**Issue by seakayone** [christiangalsterer/bitbucket-asciidoc-plugin#8]
After we installed the plugin into our Atlassian Bitbucket v4.5.1 server it renders build.gradle files und fails at it. 

Is there any possiblity to restrict the plugin to *.adoc files only?

**Comment by christiangalsterer** [comment]
Hi,

which version of the plugin have you installed?
The plugin actually only tries to render with files with the following extensions: asciidoc, adoc, ad, asc so I'm wondering why a build.gradle is file now rendered.

**Comment by seakayone** [comment]
I have not installed it myself but it is the most recent from the Atlassian Store.

**Comment by aconstantin** [comment]
@christiangalsterer we have version 2.3.0 installed.

**Comment by aconstantin** [comment]
I have provided a simple build.gradle for testing purpose. You can find this in my repository
https://github.com/aconstantin/bitbucket-asciidoc-plugin-issue8/blob/master/build.gradle

Here is a screen shot from our bitbucket server (with _active_ plugin)
<img width="1145" alt="plugin-active" src="https://cloud.githubusercontent.com/assets/1051339/15933793/67d1c444-2e61-11e6-99bb-ab0f99497861.png">

Here is a screen shot from our bitbucket server (with _inactive_ plugin)
<img width="1150" alt="plugin-inactive" src="https://cloud.githubusercontent.com/assets/1051339/15933815/79207178-2e61-11e6-8d1b-9c4ad552198c.png">

**Comment by christiangalsterer** [comment]
I have found the problem and will make a release soon.

**Comment by aconstantin** [comment]
thanks a lot, I will watch your plugin on marketplace

**Comment by christiangalsterer** [comment]
Released 2.3.1 to Atlassian Marketplace.

**Comment by aconstantin** [comment]
thanks a lot, I have updated to 2.3.1 and the problem is gone.
